# inferless-runtime-config.yaml
runtime_name: latentsync-custom-runtime # 给你的运行时起一个名字
python_version: "3.10" # 必须与项目要求一致

dependencies:
  pip:
    # 主要依赖会通过 shell_commands 中的 torch 安装和后续的 pip install 安装
    # 这里可以留空，或者只放一些不通过 shell_commands 安装的简单包
    - easydict
    - omegaconf
    - peft
    - opencv-python
    - imageio
    - tqdm
    - ftfy
    - safetensors
    - accelerate

  apt: # 系统级依赖
    - git
    - ffmpeg # 如果涉及视频或某些媒体处理

shell_commands: # 按顺序执行的 shell 命令，用于更复杂的安装
  # 安装与 CUDA 11.8 兼容的 PyTorch (根据 LatentSync 的 environment.yaml)
  # 确保 Inferless 的基础镜像支持 CUDA 11.8 或与其兼容
  - echo "Installing PyTorch for CUDA 11.8..."
  - pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118

  # 安装 diffusers 和 transformers
  - echo "Installing diffusers and transformers..."
  - pip install diffusers transformers

  # 尝试安装 xformers 和 bitsandbytes。这些包对性能很重要但安装可能复杂。
  # 如果构建失败，可以考虑先注释掉它们，或者查找特定于 Inferless 环境的精确安装命令。
  - echo "Attempting to install xformers..."
  - pip install xformers # 可能需要特定版本或编译，例如: pip install xformers==0.0.22 (查阅兼容性)

  - echo "Attempting to install bitsandbytes..."
  - pip install bitsandbytes # 同样，可能需要特定版本或有编译依赖

  - echo "Custom runtime setup complete."
